### ISSUE TITLE
Show lock on App Uninstall

### ISSUE THREAD

**Issue by thewayofknowing** [nikolamilosevic86/owasp-seraphimdroid#14]
Applock can be evaded by simply uninstalling Seraphim-droid, we can prompt for password to prevent this. As an additional feature, we can have a lock on any app uninstall in general.

**Comment by nikolamilosevic86** [comment]
Yes, this is a good idea. Seraphimdroid and locked apps should prompt for password when uninstalling.

**Comment by nikolamilosevic86** [comment]
What was the status of this at the end? I see the tick box in the settings, but it seems to me it does nothing. It is ticked by default and when I try to uninstall app, it uninstalls, nowhere in the process password is required?
