### ISSUE TITLE
Compile an in app mobile application security knowledge source

### ISSUE THREAD

**Issue by nikolamilosevic86** [nikolamilosevic86/owasp-seraphimdroid#19]
This is both documentation and development task. It is necessary to have a knowledge source as an frame in the application so users can read about various risks and threats in mobile world. Also it would be good to be uneatable database that updates data from an API hosted on for example OpenShift. OpenShift app has to have log in interface and interface where new items can be added, with risk levels. 

Permission scanner has to be updated as well with the knowledge of malicious use of permissions.

**Comment by furquan1993** [comment]
Could you please provide more details about the OpenShift app. What will be the purpose and how it is suppose to be hosted.

**Comment by nikolamilosevic86** [comment]
OpenShift is a platform as a service provider, who can provide free hosting for java, python or ruby based application with mySQL server (https://www.openshift.com/). Basic idea is to build an REST application or API that can be read by Seraphimdroid app. This API will provide content for malicious and normal use of permission as we have them now, but as well some other knowledge source (use of encryption, secure use of WiFi, etc.). Also it will provide some tree-like structure, that will generate GUI in Seraphimdroid, so maintainer of knowledge base can add, delete or modify information and it can be automatically reflected on the app, when it downloads content. Web app should have some login and administration interface where administrator and colaborators can add, edit and delete provided information. 

Does this sound good to you? Is there still something that confuses you?

**Comment by furquan1993** [comment]
This sound good. Lets decide on the REST architecture we will be using for creating a data source using OpenShift. I would like to learn using the platform as well as REST implementation while making the app better.

**Comment by nikolamilosevic86** [comment]
Of course, go for REST, it is good approach.

**Comment by addiittya2006** [comment]
Is there any significant work done or going on already on this?
Implementing an API with REST and Displaying the Knowledge Data in the separate fragment would be great.
[Assign me to this and add me to Seraphimdroid]

**Comment by nikolamilosevic86** [comment]
No, not really. You are assigned and I have added you as collaborator to the project.

**Comment by addiittya2006** [comment]
Implemented.
Please Report Bugs & Reopen Issue.
