### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [nikolamilosevic86/owasp-seraphimdroid#45]
Would you consider publishing the `.apk` here on Github as well (e.g. with the `releases/` page) – so folks without GApps/Playstore-access can get hold of it? I'd then offer to include it with [my F-Droid compatible repo](https://android.izzysoft.de/repo) for easy install/update :)

**Comment by nikolamilosevic86** [comment]
It is possible... however, we don't aim to publish it on other repositories and market places since it is huge overhead to keep them all up to date.

**Comment by IzzySoft** [comment]
That makes it hard for people w/o Playstore access to use the app. If you'd just upload/attach the `.apk` to the `releases/` (which I'd say is not that much overhead), I'd take care to have the repo updated automatically – so folks w/o Playstore access had 2 places to get it from: manually download from Github – or manually/automatically get it from the repo. Would you agree?

**Comment by addiittya2006** [comment]
As this Project is under Active Development so needs CI support. As soon as we get CI support we could do a Basic beta release on Github.

**Comment by IzzySoft** [comment]
That's a word – and thanks for considering! So I'm (patiently) looking forward to another update on this issue once CI support is given.

**Comment by addiittya2006** [comment]
Planned for August.

**Comment by IzzySoft** [comment]
Cool, thanks! Will you update this issue then once more, so I get a "ping"?

**Comment by IzzySoft** [comment]
Are the plans still true, or have things been postponed? Just humbly asking :)

**Comment by IzzySoft** [comment]
@addiittya2006 Can you refine which August you have in mind? :wink:

Apart from that, I've just opened an [RFP](https://gitlab.com/fdroid/rfp/issues/423) (request for packaging) with F-Droid. Yes, I've seen @nikolamilosevic86's comment above saying

> we don't aim to publish it on other repositories and market places since it is huge overhead to keep them all up to date.

As F-Droid would build the APKs itself, it should not be a burden onto you. You already tag new releases, so F-Droid could pick up those tags automatically even. After having set up the initial "recipe" (and you describe the build process on your README.md, so that should be no big issue for them I hope), it should "just run".

I hope that's OK with you?
