### ISSUE TITLE
update the procedure to setup project in Android studio

### ISSUE THREAD

**Issue by furquan1993** [nikolamilosevic86/owasp-seraphimdroid#46]
Currently the process explains how the project can be setup on eclipse, since the project has been moved to Android studio these instructions should also be updated.

**Comment by addiittya2006** [comment]
I shall write a wiki for this Repo and will plan a short github release after a discussion with @nikolamilosevic86 mentioning all the steps for build and would be updating the README

**Comment by addiittya2006** [comment]
Done in #48 .
Review and Merge.
