### ISSUE TITLE
Modifiable USSD codes

### ISSUE THREAD

**Issue by nikolamilosevic86** [nikolamilosevic86/owasp-seraphimdroid#6]
Alow user to modify list of blocked USSD codes. Different USSD codes may mean different things in a different devices and with different operators. There should be a list with a meaning of predefined USSD codes, but also user should be allowed to remove, edit and add new USSD codes.

**Comment by thewayofknowing** [comment]
IMHO We can have an options in the settings page, and then a listview showing current USSD codes. The user can delete/add new codes. The predefined USSD list can be made non-editable

**Comment by nikolamilosevic86** [comment]
Yes, that is exactly the idea
