### ISSUE TITLE
Application lock Bypass bug

### ISSUE THREAD

**Issue by a0xnirudh** [nikolamilosevic86/owasp-seraphimdroid#7]
I have recently installed OWASP seraphimdroid app in my android 4.4.4 and I tried to lock the main apps with the Application lock provided. While I was playing around (to see if there is any bugs), I noted that the application lock can be bypassed easily.

Steps to reproduce:
1) Lock any app, say WhatsApp, with the Application locker.
2) Try to open WhatsApp and the application locker password will be asked. 
3) Instead of typing the password, click the App switch button and now you can see 2 apps running namely WhatsApp and the seraphimdroid.
4) Simply close the seraphimdroid app and click on WhatsApp and there, WhatsApp is unlocked.

The reason why this could be happening is because while the password is being asked, the application is also shown as a current running app which should not be seen or if user tends to close it, then the locked program also should quit.

**Comment by furquan1993** [comment]
Hi Aniruddh,

The code has been written so as not to show the SeraphimDroid in the recent
tasks. You can have a look, the problem might be persisting in your device.

If you could find the other solution, that is to close the locked
application when you close SeraphimDroid, you are welcome to submit the
patch.

**Comment by nikolamilosevic86** [comment]
This is actually a bug and should be fixed soon.

**Comment by F0x7r0t** [comment]
Yes and also the app is not combatible with the Android 5.0 Lollipop (atleast for me). The app is working alright but after I locked certain items, when I tried to open the same locked items, there was't a prompt for password.

**Comment by nikolamilosevic86** [comment]
I believe you are right. It also happened to my Nexus 5 phone when updated to Lollipop. Thank you for reporting the issue. If you found more, let us know.
