### ISSUE TITLE
Applications not sorted completely

### ISSUE THREAD

**Issue by thewayofknowing** [nikolamilosevic86/owasp-seraphimdroid#9]
Tested on: Android KitKat (4.4.4)
![screenshot_2015-02-16-09-51-26](https://cloud.githubusercontent.com/assets/4375956/6207417/59b6b9f8-b5c9-11e4-8bfb-14a984f80b4c.png)

**Comment by nikolamilosevic86** [comment]
Is this done?

**Comment by thewayofknowing** [comment]
Yes, it was resolved in my last commit.

**Comment by nikolamilosevic86** [comment]
Ok, closing the issue
